language: php

jobs:
  fast_finish: false
  include:
    - os: linux
      dist: precise
      php: 5.3
      sudo: required
    - os: linux
      dist: trusty
      php: 5.4
      sudo: required
    - os: linux
      dist: trusty
      php: 5.5
      sudo: required
    - os: linux
      dist: trusty
      php: 5.6
      sudo: required
    - os: linux
      dist: xenial
      php: 7.0
      sudo: required
    - os: linux
      dist: xenial
      php: 7.1
      sudo: required
    - os: linux
      dist: xenial
      php: 7.2
      sudo: required
    - os: linux
      dist: xenial
      php: 7.3
      sudo: required
    - os: linux
      dist: bionic
      php: 7.4
      sudo: required
    - os: linux
      dist: bionic
      php: 8.0
      sudo: required

before_install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer self-update

install:
  - composer install

script:
  - php ./tests/run_all.php

